version: "3.9"
networks:
  prometheus-network:
volumes:
  prometheus-data:
  grafana-data:
services:
  prometheus:
    image: ubuntu/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus-data:/var/lib/prometheus/data
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus-network
    ports:
      - 9090:9090
    restart: unless-stopped
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana 
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000 
    networks:
      - prometheus-network
    restart: unless-stopped
  prometheus-blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: prometheus-blackbox-exporter
    networks:
      - prometheus-network
    restart: unless-stopped
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter:latest
    container_name: speedtest-exporter
    environment:
      - SPEEDTEST_SERVER=20912 # Cool Ideas Cape Town
    networks:
      - prometheus-network
    restart: unless-stopped
  smokeping-exporter:
    image: quay.io/superq/smokeping-prober:latest
    container_name: smokeping-exporter
    volumes:
      - ./config/smokeping_exporter.yml:/config.yml
    command: ["--config.file=config.yml"]
    networks:
      - prometheus-network
    restart: unless-stopped
