version: "3.9"
networks:
  prometheus_network:
volumes:
  prometheus_data:
  grafana_data:
services:
  prometheus:
    image: ubuntu/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/var/lib/prometheus/data
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus_network
    ports:
      - 9090:9090
    restart: unless-stopped
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana 
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - 3000:3000 
    networks:
      - prometheus_network
    restart: unless-stopped
  speetest-probe:
    # https://docs.miguelndecarvalho.pt/projects/speedtest-exporter/
    image: miguelndecarvalho/speedtest-exporter:latest
    container_name: speedtest-probe
    environment:
      - SPEEDTEST_SERVER=20912 # Cool Ideas Cape Town
    networks:
      - prometheus_network
    restart: unless-stopped
  smokeping-probe:
    # https://github.com/SuperQ/smokeping_prober
    image: quay.io/superq/smokeping-prober:latest
    container_name: smokeping-probe
    volumes:
      - ./config/smokeping_prober.yml:/config.yml
    command: ["--config.file=config.yml"]
    networks:
      - prometheus_network
    restart: unless-stopped
