global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "speedtest-exporter"
    scrape_interval: 5m
    scrape_timeout: 2m
    static_configs:
      - targets: ["speedtest-exporter:9798"]

  - job_name: "smokeping-exporter"
    scrape_interval: 1m
    scrape_timeout: 15s
    static_configs:
      - targets: ["smokeping-exporter:9374"]
