global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: "speedtest-exporter"
    scrape_interval: 5m
    scrape_timeout: 2m
    static_configs:
      - targets: ["speedtest-exporter:9798"]

  - job_name: "smokeping-exporter"
    scrape_interval: 1m
    scrape_timeout: 15s
    static_configs:
      - targets: ["smokeping-exporter:9374"]

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [icmp]
    scrape_interval: 15s
    static_configs:
      - targets:
        - 1.1.1.1
        - 8.8.8.8
        - 192.168.0.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox-exporter:9115
